name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm test
      env:
        CI: true
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        JOB_CONTEXT: ${{ toJson(job) }}
        RUNNER_CONTEXT: ${{ toJson(runner) }}
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
        STEPS_CONTEXT: ${{ toJson(steps) }}
        GITHUB_CONTEXT: ${{ toJson(github) }}
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      if: matrix['node-version'] == strategy.matrix['node-version'][-1]
      with:
        name: code-coverage-${{ matrix.node-version }}
        path: test/reports/unit/lcov-report
